site_name: apstra-api-python
site_dir: apstra-api-python/project-static/docs
site_url: https://apstra-api-python.readthedocs.io/
repo_name: apstra/apstra-api-python
repo_url: https://github.com/apstra/apstra-api-python
edit_uri: ""
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github-square
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
nav:
  - Home: 'index.md'
  - Getting Started: 'getstarted.md'
  - API Introduction: 'api-introduction.md'
  - Solutions and Examples:
      - Login to Apstra: 'example-scripts/apstra_login.md'
      - Managed Devices: 'example-scripts/managed_devices.md'
      - Resources: 'example-scripts/resource_pools.md'
      - Design:
        - Rack Types: 'example-scripts/design/rack_types.md'
        - Templates: 'example-scripts/design/templates.md'
      - Blueprint:
        - Create: 'example-scripts/blueprint/create.md'
        - Graph Queries: 'example-scripts/blueprint/graph_queries.md'
        - Assign Interface Maps: 'example-scripts/blueprint/assign_interface_maps.md'
        - Assign Devices: 'example-scripts/blueprint/assign_devices.md'
        - Assign Resources: 'example-scripts/blueprint/resources.md'
        - Virtual Networks: 'example-scripts/blueprint/virtual_network.md'
        - Routing Zone: 'example-scripts/blueprint/routing_zone.md'
        - Connectivity Template: 'example-scripts/blueprint/connectivity_template.md'
        - External Generic System: 'example-scripts/blueprint/external_generic_system.md'
        - Commit Changes: 'example-scripts/blueprint/commit.md'
  - Code Reference:
      - AOS: aos-reference.md
      - Blueprint: blueprint-reference.md
      - Client: client-reference.md
      - Design: design-reference.md
      - Devices: devices-reference.md
